import React, { createContext, useState, useContext, ReactNode } from 'react';


// Allow any string to support the full list from SUPPORTED_LANGUAGES, 
// allows 'es-la', 'en-us' as legacy or full names.
type Language = string;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  'es-la': {
    // --- SETTINGS (Existing) ---
    'settings.title': 'Ajustes de Idioma y Región',
    'settings.desc': 'Personaliza tu experiencia en PACTO para que se adapte a tu ubicación y preferencias de trabajo.',
    'label.language': 'Idioma de la plataforma',
    'label.region': 'País/Región',
    'label.timezone': 'Zona Horaria',
    'label.dateformat': 'Formato de Fecha/Hora',
    'settings.date_format.dmy_24': 'DD/MM/AAAA (24h)',
    'settings.date_format.dmy_12': 'DD/MM/AAAA (12h am/pm)',
    'settings.date_format.mdy_12': 'MM/DD/AAAA (12h am/pm)',
    'settings.date_format.ymd_24': 'AAAA-MM-DD (24h)',
    'tip.title': '¿Por qué es importante esto?',
    'tip.desc': 'Configurar tu zona horaria correcta ayuda a tu equipo a respetar tus horas de "Deep Work" y sincronizar mejor las reuniones.',
    'btn.cancel': 'Cancelar',
    'btn.save': 'Guardar cambios',
    'btn.saving': 'Guardando...',
    'region.select': 'Selecciona tu país',
    'timezone.select': 'Seleccionar...',
    'back': 'Volver',

    // --- NAVIGATION ---
    'nav.dashboard': 'Inicio',
    'nav.my_agreements': 'Mis Acuerdos',
    'nav.my_commitments': 'Mis Compromisos',
    'nav.team': 'Mi Equipo',
    'nav.rituals': 'Rituales',
    'nav.achievements': 'Logros',
    'nav.inbox': 'Buzón',
    'nav.reports': 'Reportes',
    'nav.clarity_kits': 'Kits de Claridad',
    'nav.profile': 'Mi Perfil',
    'nav.help': 'Ayuda',
    'nav.logout': 'Cerrar Sesión',

    // --- TIMEZONES ---
    'timezone.utc-12': 'Línea internacional de fecha del oeste',
    'timezone.utc-11': 'Isla Midway, Samoa',
    'timezone.utc-10': 'Hawái',
    'timezone.utc-09': 'Alaska',
    'timezone.utc-08': 'Hora del Pacífico (USA y Canadá)',
    'timezone.utc-07': 'Hora de la Montaña (USA y Canadá)',
    'timezone.utc-06': 'Hora Central (USA y Canadá), CDMX',
    'timezone.utc-05': 'Hora del Este (USA y Canadá), Bogotá',
    'timezone.utc-04': 'Hora del Atlántico (Canadá), Santiago',
    'timezone.utc-03': 'Buenos Aires, Brasilia',
    'timezone.utc-02': 'Atlántico Central',
    'timezone.utc-01': 'Azores, Cabo Verde',
    'timezone.utc+00': 'Londres, Dublín, Lisboa',
    'timezone.utc+01': 'Madrid, París, Berlín, Roma',
    'timezone.utc+02': 'Atenas, Bucarest, Estambul',
    'timezone.utc+03': 'Moscú, San Petersburgo',
    'timezone.utc+04': 'Abu Dabi, Mascate',
    'timezone.utc+05': 'Islamabad, Karachi',
    'timezone.utc+06': 'Almaty, Dhaka',
    'timezone.utc+07': 'Bangkok, Hanoi, Yakarta',
    'timezone.utc+08': 'Pekín, Hong Kong, Singapur',
    'timezone.utc+09': 'Tokio, Seúl',
    'timezone.utc+10': 'Sídney, Melbourne',
    'timezone.utc+11': 'Islas Salomón, Nueva Caledonia',
    'timezone.utc+12': 'Fiyi, Kamchatka',

    // --- LANDING PAGE ---
    'landing.nav.mission': 'Misión',
    'landing.nav.pillars': 'Pilares',
    'landing.nav.tools': 'Herramientas',
    'landing.nav.start': 'Empezar',
    'landing.hero.badge': 'Innovación Neurodiversa',
    'landing.hero.title': 'De la intención a la práctica',
    'landing.hero.subtitle': 'Una plataforma digital diseñada para la inclusión neurodiversa y acuerdos operativos reales. Accesible, clara y construida para humanos.',
    'landing.hero.cta': 'Crear mi cuenta',
    'landing.pillars.title': 'Nuestros Pilares',
    'landing.pillars.subtitle': 'PACTO reduce la carga cognitiva priorizando la estructura visual y la seguridad psicológica.',
    'landing.pillars.1.title': 'Seguridad Psicológica',
    'landing.pillars.1.desc': 'Creamos ciclos de retroalimentación seguros donde cada miembro comparte sus necesidades cognitivas.',
    'landing.pillars.2.title': 'Claridad Operativa',
    'landing.pillars.2.desc': 'Eliminamos la ambigüedad. Definimos expectativas claras y canales efectivos para todos.',
    'landing.pillars.3.title': 'Neuro-Inclusión',
    'landing.pillars.3.desc': 'Herramientas creadas para acomodar TDAH, Autismo y diversos estilos de procesamiento.',
    'landing.tools.title': 'Herramientas Visuales',
    'landing.tools.subtitle': 'Diseñamos interfaces que reducen el ruido y maximizan la claridad.',
    'landing.tools.1.title': 'Canvas de Acuerdos',
    'landing.tools.1.desc': 'Visualiza todas las normas operativas en un solo lugar accesible.',
    'landing.tools.2.title': 'Kits de Claridad',
    'landing.tools.2.desc': 'Tarjetas pre-diseñadas para resolver conflictos comunes de comunicación.',
    'landing.tools.3.title': 'Rituales de Replay',
    'landing.tools.3.desc': 'Estructuras para reuniones que aseguran que todos estén alineados.',
    'landing.cta.title': '¿Listo para construir una cultura verdaderamente inclusiva?',
    'landing.cta.subtitle': 'Únete a empresas que ya usan PACTO para mejorar la claridad y la empatía operativa.',
    'landing.cta.btn': 'Empezar gratis hoy',
    'landing.footer.desc': 'Plataforma de acuerdos vivos para la inclusión laboral neurodiversa. Diseñamos estructuras que permiten a cada mente trabajar mejor.',

    // --- RITUALS ---
    'ritual.title': 'Rituales de Equipo',
    'ritual.desc': 'Gestiona tu energía cognitiva y colaborativa. Sin cuadrículas, solo claridad.',
    'ritual.view.scheduled': 'Programados',
    'ritual.view.prep': 'Por Preparar',
    'ritual.view.drafts': 'Borradores',
    'ritual.view.archived': 'Archivados',
    'ritual.btn.schedule': 'Programar',
    'ritual.section.today': 'Hoy',
    'ritual.energy.load': 'Carga',
    'ritual.energy.level.high': 'Alto',
    'ritual.energy.level.medium': 'Medio',
    'ritual.energy.level.optimal': 'Óptimo',
    'ritual.energy.level.low': 'Baja',
    'ritual.empty.title': 'Tu agenda de rituales está vacía',
    'ritual.empty.desc': 'Los rituales ayudan a tu equipo a sincronizarse sin agotar su energía. ¡Crea el primero ahora!',
    'ritual.btn.create_first': 'Crear mi primer ritual',

    // Ritual Types & Status
    'ritual.type.sync': 'Sincronización',
    'ritual.type.focus': 'Foco Profundo',
    'ritual.type.social': 'Social',
    'ritual.type.strategy': 'Estrategia',
    'ritual.status.completed': 'Completado',
    'ritual.status.automatic': 'Automático',
    'ritual.status.no_notifications': 'Sin notificaciones',

    // Preparation View
    'ritual.prep.attention': 'Requiere Atención',
    'ritual.prep.desc': 'Tienes rituales próximos que aún no tienen agenda o materiales preparados.',
    'ritual.prep.next': 'Próximo Ritual',
    'ritual.prep.btn': 'Preparar Ahora',
    'ritual.prep.no_participants': 'Sin Agenda',
    'ritual.prep.participants': 'participantes',
    'ritual.prep.empty': 'No hay más rituales pendientes de preparación.',

    // Drafts & Archived
    'ritual.drafts.empty.title': 'No hay borradores',
    'ritual.drafts.btn': 'Crear nuevo ritual',
    'ritual.archived.restore': 'Restaurar',
    'ritual.history.btn': 'Ver historial completo',
    'ritual.history.link': 'Ver historial de rituales pasados',

    // Widgets (Right Sidebar)
    'ritual.widget.energy.title': 'Sugerencias de Energía',
    'ritual.widget.analysis': 'Análisis de hoy',
    'ritual.widget.level': 'Nivel de Carga',
    'ritual.widget.msg.high': 'Hemos detectado {count} rituales. Tu carga cognitiva está por encima del promedio recomendado.',
    'ritual.widget.msg.optimal': 'Tu carga de rituales está equilibrada. Buen momento para trabajo profundo.',
    'ritual.widget.suggestion': 'Sugerencia: Bloquea 15 min después del almuerzo para desconexión sensorial.',

    'ritual.widget.tools.title': 'Herramientas Rápidas',
    'ritual.widget.pomodoro': 'Modo Pomodoro',
    'ritual.widget.pomodoro.desc': '25m enfoque / 5m descanso',
    'ritual.widget.mute': 'Silenciar Todo',
    'ritual.widget.mute.desc': 'Hasta las 05:00 PM',
    'ritual.widget.calendar.events': 'Eventos de Equipo',

    // --- ADMIN DASHBOARD ---
    'admin.badge': 'Vista de Administrador',
    'admin.title': 'Panel de Control',
    'admin.subtitle': 'Gestión global de {name}.',
    'admin.btn.switch': 'Ir a mi Perfil Personal',
    'admin.metric.health': 'Salud Organizacional',
    'admin.metric.health.desc': 'Basado en adopción de acuerdos y feedback.',
    'admin.metric.members': 'Miembros Activos',
    'admin.metric.members.suffix': 'licencias',
    'admin.metric.agreements': 'Acuerdos Vigentes',
    'admin.metric.agreements.total': 'Total',
    'admin.btn.manage_team': 'Gestionar Equipo',
    'admin.btn.templates': 'Ver Biblioteca de Plantillas',
    'admin.actions.title': 'Acciones Rápidas',
    'admin.action.invite': 'Invitar Usuarios',
    'admin.action.teams': 'Gestionar Equipos',
    'admin.action.reports': 'Ver Reportes',
    'admin.action.accessibility': 'Configurar Accesibilidad',
    'admin.activity.title': 'Actividad de la Organización',

    // --- DASHBOARD ---
    'dash.welcome': 'Hola, {name}',
    'dash.subtitle': 'Tu espacio personal de claridad y acuerdos.',
    'dash.btn.library': 'Explorar Biblioteca',
    'dash.btn.new': 'Nuevo Acuerdo',
    'dash.section.agreements': 'Mis Acuerdos Vivos',
    'dash.link.viewall': 'Ver todos',
    'dash.empty.title': 'Aún no tienes acuerdos',
    'dash.empty.desc': 'Crea uno nuevo para mejorar la claridad con tu equipo.',
    'dash.empty.btn': 'Crear mi primer acuerdo',
    'dash.widget.wellbeing': 'Mi Bienestar',
    'dash.widget.clarity': 'Claridad',
    'dash.widget.tostart': 'Por iniciar',
    'dash.widget.ready': '¡Todo listo! Estás alineado y listo para colaborar.',
    'dash.widget.nodata': 'Aún no hay datos. Crea tu primer Acuerdo Vivo.',
    'dash.tools.title': 'Herramientas Personales',
    'dash.tools.focus.active': 'Foco Activo',
    'dash.tools.focus.start': 'Iniciar Modo Foco',
    'dash.tools.focus.muting': 'Silenciando notificaciones',
    'dash.tools.focus.desc': 'Silenciar notificaciones por 1h',
    'dash.tools.clarity.title': 'Consultar Clarity Cards',
    'dash.tools.clarity.desc': 'Guías visuales de comunicación',
    'dash.tip.title': 'Tip del Día',
    'dash.tip.btn.idle': 'Enviar Tip al Equipo',
    'dash.tip.btn.sending': 'Enviando...',
    'dash.tip.btn.success': '¡Enviado!',

    // --- GLOBAL ---
    'global.menu': 'Menú',
    'global.back_home': 'Volver al Inicio',
    'global.notifications': 'Notificaciones',
    'global.brand_suffix': 'by Teamworkz',
    'global.copyright': 'Todos los derechos reservados.',
    'global.rights': 'WCAG 2.2 Level AAA Compliant',
    'global.btn.close': 'Cerrar',

    // --- LAYOUT ---
    'layout.mobile.menu': 'Menú',
    'layout.mobile.back': 'Volver al Inicio',

    // --- LANDING FOOTER ---
    'landing.footer.platform': 'Plataforma',
    'landing.footer.legal': 'Legal',
    'landing.footer.mission': 'Nuestra Misión',
    'landing.footer.success': 'Casos de Éxito',
    'landing.footer.pricing': 'Precios',
    'landing.footer.contact': 'Formulario de Contacto',
    'landing.footer.accessibility': 'Declaración de Accesibilidad',
    'landing.footer.privacy': 'Política de Privacidad',
    'landing.footer.cookies': 'Política de Cookies',
    'landing.footer.legal_notice': 'Aviso Legal',

    // --- DASHBOARD ---
    'dash.view.personal': 'Vista Personal',
    'dash.view.admin': 'Vista de Admin',
    'dash.return_admin': 'Volver al Panel Admin',
    'dash.tag.inclusion': 'Inclusión',
    'dash.tag.wellbeing': 'Bienestar',

    // --- RITUALS ---
    'ritual.view.label': 'Vistas',
    'ritual.card.prepare.title': 'Replay Semanal',
    'ritual.card.prepare.desc': 'Sincronización de equipo. Revisa los acuerdos previos y define el tono de la sesión.',

    // --- NEW RITUAL ---
    'new_ritual.title': 'Nuevo Ritual de Replay',
    'new_ritual.subtitle': 'Define los detalles para tu próxima sesión de alineación.',
    'new_ritual.btn.close': 'Cerrar',
    'new_ritual.accessibility.title': 'Sugerencia de Accesibilidad',
    'new_ritual.accessibility.desc': 'Enviar la agenda con 24 horas de antelación ayuda a que todos los participantes se preparen mejor y reduce la ansiedad.',
    'new_ritual.accessibility.link': 'Ver más tips',
    'new_ritual.label.title': 'Título del Ritual',
    'new_ritual.placeholder.title': 'Ej. Sincronización Semanal de Diseño',
    'new_ritual.label.date': 'Fecha',
    'new_ritual.label.time': 'Hora',
    'new_ritual.label.participants': 'Participantes',
    'new_ritual.placeholder.participants': 'Añadir + Enter...',
    'new_ritual.label.objective': 'Objetivo de la Sesión',
    'new_ritual.placeholder.objective': 'Describe brevemente lo que se espera lograr en esta sesión...',
    'new_ritual.section.agreements': 'Vincular Acuerdos Activos',
    'new_ritual.section.agreements.desc': 'Selecciona un acuerdo para añadirlo automáticamente a la agenda de revisión.',
    'new_ritual.section.agenda': 'Agenda del Ritual',
    'new_ritual.btn.add_agreement': 'Añadir otro acuerdo',
    'new_ritual.btn.cancel': 'Cancelar',
    'new_ritual.btn.submit': 'Programar Ritual',

    // --- APP TITLES ---
    'page.mission': 'Nuestra Misión',
    'page.success': 'Casos de Éxito',
    'page.pricing': 'Precios',
    'page.accessibility': 'Declaración de Accesibilidad',
    'page.privacy': 'Política de Privacidad',
    'page.cookies': 'Política de Cookies',
    'page.legal': 'Aviso Legal',
    'page.mission.content': 'Empoderar a equipos neurodiversos a través de la claridad y la empatía.',
    'page.success.content': 'Descubre cómo empresas líderes están transformando su cultura.',
    'page.pricing.content': 'Planes flexibles para equipos de todos los tamaños.',
    'page.accessibility.content': 'Comprometidos con WCAG 2.2 AAA.',
    'page.privacy.content': 'Tus datos son tuyos. Transparencia total.',
    'page.cookies.content': 'Solo lo esencial para que la plataforma funcione.',
    'page.legal.content': 'Información legal de Teamworkz.',
  },
  'en-us': {
    // --- SETTINGS (Existing) ---
    'settings.title': 'Language & Region Settings',
    'settings.desc': 'Customize your PACTO experience to match your location and work preferences.',
    'label.language': 'Platform Language',
    'label.region': 'Country/Region',
    'label.timezone': 'Timezone',
    'label.dateformat': 'Date/Time Format',
    'settings.date_format.dmy_24': 'DD/MM/YYYY (24h)',
    'settings.date_format.dmy_12': 'DD/MM/YYYY (12h am/pm)',
    'settings.date_format.mdy_12': 'MM/DD/YYYY (12h am/pm)',
    'settings.date_format.ymd_24': 'YYYY-MM-DD (24h)',
    'tip.title': 'Why is this important?',
    'tip.desc': 'Setting your correct timezone helps your team respect your "Deep Work" hours and synchronize meetings better.',
    'btn.cancel': 'Cancel',
    'btn.save': 'Save Changes',
    'btn.saving': 'Saving...',
    'region.select': 'Select your country',
    'timezone.select': 'Select...',
    'back': 'Back',

    // --- NAVIGATION ---
    'nav.dashboard': 'Home',
    'nav.my_agreements': 'My Agreements',
    'nav.my_commitments': 'My Commitments',
    'nav.team': 'My Team',
    'nav.rituals': 'Rituals',
    'nav.achievements': 'Achievements',
    'nav.inbox': 'Inbox',
    'nav.reports': 'Reports',
    'nav.clarity_kits': 'Clarity Kits',
    'nav.profile': 'My Profile',
    'nav.help': 'Help Center',
    'nav.logout': 'Log Out',

    // --- TIMEZONES ---
    'timezone.utc-12': 'International Date Line West',
    'timezone.utc-11': 'Midway Island, Samoa',
    'timezone.utc-10': 'Hawaii',
    'timezone.utc-09': 'Alaska',
    'timezone.utc-08': 'Pacific Time (US & Canada)',
    'timezone.utc-07': 'Mountain Time (US & Canada)',
    'timezone.utc-06': 'Central Time (US & Canada), Mexico City',
    'timezone.utc-05': 'Eastern Time (US & Canada), Bogota',
    'timezone.utc-04': 'Atlantic Time (Canada), Santiago',
    'timezone.utc-03': 'Buenos Aires, Brasilia',
    'timezone.utc-02': 'Mid-Atlantic',
    'timezone.utc-01': 'Azores, Cape Verde',
    'timezone.utc+00': 'London, Dublin, Lisbon',
    'timezone.utc+01': 'Madrid, Paris, Berlin, Rome',
    'timezone.utc+02': 'Athens, Bucharest, Istanbul',
    'timezone.utc+03': 'Moscow, St. Petersburg',
    'timezone.utc+04': 'Abu Dhabi, Muscat',
    'timezone.utc+05': 'Islamabad, Karachi',
    'timezone.utc+06': 'Almaty, Dhaka',
    'timezone.utc+07': 'Bangkok, Hanoi, Jakarta',
    'timezone.utc+08': 'Beijing, Hong Kong, Singapore',
    'timezone.utc+09': 'Tokyo, Seoul',
    'timezone.utc+10': 'Sydney, Melbourne',
    'timezone.utc+11': 'Solomon Is., New Caledonia',
    'timezone.utc+12': 'Fiji, Kamchatka',

    // --- LANDING PAGE ---
    'landing.nav.mission': 'Mission',
    'landing.nav.pillars': 'Pillars',
    'landing.nav.tools': 'Tools',
    'landing.nav.start': 'Start',
    'landing.hero.badge': 'Neurodiverse Innovation',
    'landing.hero.title': 'From Intention to Practice',
    'landing.hero.subtitle': 'A digital platform designed for neurodiverse inclusion and real operational agreements. Accessible, clear, and built for humans.',
    'landing.hero.cta': 'Create my account',
    'landing.pillars.title': 'Our Pillars',
    'landing.pillars.subtitle': 'PACTO reduces cognitive load by prioritizing visual structure and psychological safety.',
    'landing.pillars.1.title': 'Psychological Safety',
    'landing.pillars.1.desc': 'We create safe feedback loops where every member shares their cognitive needs.',
    'landing.pillars.2.title': 'Operational Clarity',
    'landing.pillars.2.desc': 'We eliminate ambiguity. We define clear expectations and effective channels for everyone.',
    'landing.pillars.3.title': 'Neuro-Inclusion',
    'landing.pillars.3.desc': 'Tools created to accommodate ADHD, Autism, and diverse processing styles.',
    'landing.tools.title': 'Visual Tools',
    'landing.tools.subtitle': 'We design interfaces that reduce noise and maximize clarity.',
    'landing.tools.1.title': 'Agreements Canvas',
    'landing.tools.1.desc': 'Visualize all operational norms in one accessible place.',
    'landing.tools.2.title': 'Clarity Kits',
    'landing.tools.2.desc': 'Pre-designed cards to resolve common communication conflicts.',
    'landing.tools.3.title': 'Replay Rituals',
    'landing.tools.3.desc': 'Meeting structures that ensure everyone is aligned.',
    'landing.cta.title': 'Ready to build a truly inclusive culture?',
    'landing.cta.subtitle': 'Join companies already using PACTO to improve clarity and operational empathy.',
    'landing.cta.btn': 'Start for free today',
    'landing.footer.desc': 'Living agreements platform for neurodiverse workplace inclusion. We design structures that allow every mind to work better.',

    // --- RITUALS ---
    'ritual.title': 'Team Rituals',
    'ritual.desc': 'Manage your cognitive and collaborative energy. No grids, just clarity.',
    'ritual.view.scheduled': 'Scheduled',
    'ritual.view.prep': 'To Prepare',
    'ritual.view.drafts': 'Drafts',
    'ritual.view.archived': 'Archived',
    'ritual.btn.schedule': 'Schedule',
    'ritual.section.today': 'Today',
    'ritual.energy.load': 'Load',
    'ritual.energy.level.high': 'High',
    'ritual.energy.level.medium': 'Medium',
    'ritual.energy.level.optimal': 'Optimal',
    'ritual.energy.level.low': 'Low',
    'ritual.empty.title': 'Your ritual agenda is empty',
    'ritual.empty.desc': 'Rituals help your team sync without draining energy. Create your first one now!',
    'ritual.btn.create_first': 'Create my first ritual',

    // Ritual Types & Status
    'ritual.type.sync': 'Sync',
    'ritual.type.focus': 'Deep Focus',
    'ritual.type.social': 'Social',
    'ritual.type.strategy': 'Strategy',
    'ritual.status.completed': 'Completed',
    'ritual.status.automatic': 'Automatic',
    'ritual.status.no_notifications': 'No notifications',

    // Preparation View
    'ritual.prep.attention': 'Requires Attention',
    'ritual.prep.desc': 'You have upcoming rituals that do not have an agenda or materials prepared yet.',
    'ritual.prep.next': 'Next Ritual',
    'ritual.prep.btn': 'Prepare Now',
    'ritual.prep.no_participants': 'No Agenda',
    'ritual.prep.participants': 'participants',
    'ritual.prep.empty': 'No more rituals pending preparation.',

    // Drafts & Archived
    'ritual.drafts.empty.title': 'No drafts',
    'ritual.drafts.btn': 'Create new ritual',
    'ritual.archived.restore': 'Restore',
    'ritual.history.btn': 'View full history',
    'ritual.history.link': 'View past ritual history',

    // Widgets (Right Sidebar)
    'ritual.widget.energy.title': 'Energy Suggestions',
    'ritual.widget.analysis': 'Today\'s Analysis',
    'ritual.widget.level': 'Load Level',
    'ritual.widget.msg.high': 'We detected {count} rituals. Your cognitive load is above the recommended average.',
    'ritual.widget.msg.optimal': 'Your ritual load is balanced. Good time for deep work.',
    'ritual.widget.suggestion': 'Suggestion: Block 15 min after lunch for sensory disconnection.',

    'ritual.widget.tools.title': 'Quick Tools',
    'ritual.widget.pomodoro': 'Pomodoro Mode',
    'ritual.widget.pomodoro.desc': '25m focus / 5m break',
    'ritual.widget.mute': 'Mute All',
    'ritual.widget.mute.desc': 'Until 05:00 PM',
    'ritual.widget.calendar.events': 'Team Events',

    // --- ADMIN DASHBOARD ---
    'admin.badge': 'Admin View',
    'admin.title': 'Control Panel',
    'admin.subtitle': 'Global management of {name}.',
    'admin.btn.switch': 'Go to Personal Profile',
    'admin.metric.health': 'Organizational Health',
    'admin.metric.health.desc': 'Based on agreement adoption and feedback.',
    'admin.metric.members': 'Active Members',
    'admin.metric.members.suffix': 'licenses',
    'admin.metric.agreements': 'Active Agreements',
    'admin.metric.agreements.total': 'Total',
    'admin.btn.manage_team': 'Manage Team',
    'admin.btn.templates': 'View Template Library',
    'admin.actions.title': 'Quick Actions',
    'admin.action.invite': 'Invite Users',
    'admin.action.teams': 'Manage Teams',
    'admin.action.reports': 'View Reports',
    'admin.action.accessibility': 'Configure Accessibility',
    'admin.activity.title': 'Organization Activity',

    // --- DASHBOARD ---
    'dash.welcome': 'Hello, {name}',
    'dash.subtitle': 'Your personal space for clarity and agreements.',
    'dash.btn.library': 'Explore Library',
    'dash.btn.new': 'New Agreement',
    'dash.section.agreements': 'My Living Agreements',
    'dash.link.viewall': 'View all',
    'dash.empty.title': 'No agreements yet',
    'dash.empty.desc': 'Create a new one to improve clarity with your team.',
    'dash.empty.btn': 'Create my first agreement',
    'dash.widget.wellbeing': 'My Wellbeing',
    'dash.widget.clarity': 'Clarity',
    'dash.widget.tostart': 'To start',
    'dash.widget.ready': 'All set! You are aligned and ready to collaborate.',
    'dash.widget.nodata': 'No data yet. Create your first Living Agreement.',
    'dash.tools.title': 'Personal Tools',
    'dash.tools.focus.active': 'Focus Active',
    'dash.tools.focus.start': 'Start Focus Mode',
    'dash.tools.focus.muting': 'Muting notifications',
    'dash.tools.focus.desc': 'Mute notifications for 1h',
    'dash.tools.clarity.title': 'View Clarity Cards',
    'dash.tools.clarity.desc': 'Visual communication guides',
    'dash.tip.title': 'Tip of the Day',
    'dash.tip.btn.idle': 'Send Tip to Team',
    'dash.tip.btn.sending': 'Sending...',
    'dash.tip.btn.success': 'Sent!',

    // --- GLOBAL ---
    'global.menu': 'Menu',
    'global.back_home': 'Back to Home',
    'global.notifications': 'Notifications',
    'global.brand_suffix': 'by Teamworkz',
    'global.copyright': 'All rights reserved.',
    'global.rights': 'WCAG 2.2 Level AAA Compliant',
    'global.btn.close': 'Close',

    // --- LAYOUT ---
    'layout.mobile.menu': 'Menu',
    'layout.mobile.back': 'Back to Home',

    // --- LANDING FOOTER ---
    'landing.footer.platform': 'Platform',
    'landing.footer.legal': 'Legal',
    'landing.footer.mission': 'Our Mission',
    'landing.footer.success': 'Success Stories',
    'landing.footer.pricing': 'Pricing',
    'landing.footer.contact': 'Contact Form',
    'landing.footer.accessibility': 'Accessibility Statement',
    'landing.footer.privacy': 'Privacy Policy',
    'landing.footer.cookies': 'Cookie Policy',
    'landing.footer.legal_notice': 'Legal Notice',

    // --- DASHBOARD ---
    'dash.view.personal': 'Personal View',
    'dash.view.admin': 'Admin View',
    'dash.return_admin': 'Back to Admin Panel',
    'dash.tag.inclusion': 'Inclusion',
    'dash.tag.wellbeing': 'Wellbeing',

    // --- RITUALS ---
    'ritual.view.label': 'Views',
    'ritual.card.prepare.title': 'Weekly Replay',
    'ritual.card.prepare.desc': 'Team synchronization. Review previous agreements and set the tone for the session.',

    // --- NEW RITUAL ---
    'new_ritual.title': 'New Replay Ritual',
    'new_ritual.subtitle': 'Define details for your next alignment session.',
    'new_ritual.btn.close': 'Close',
    'new_ritual.accessibility.title': 'Accessibility Tip',
    'new_ritual.accessibility.desc': 'Sending the agenda 24 hours in advance helps all participants prepare better and reduces anxiety.',
    'new_ritual.accessibility.link': 'See more tips',
    'new_ritual.label.title': 'Ritual Title',
    'new_ritual.placeholder.title': 'E.g. Design Weekly Sync',
    'new_ritual.label.date': 'Date',
    'new_ritual.label.time': 'Time',
    'new_ritual.label.participants': 'Participants',
    'new_ritual.placeholder.participants': 'Add + Enter...',
    'new_ritual.label.objective': 'Session Objective',
    'new_ritual.placeholder.objective': 'Briefly describe what is expected to be achieved in this session...',
    'new_ritual.section.agreements': 'Link Active Agreements',
    'new_ritual.section.agreements.desc': 'Select an agreement to automatically add it to the review agenda.',
    'new_ritual.section.agenda': 'Ritual Agenda',
    'new_ritual.btn.add_agreement': 'Add another agreement',
    'new_ritual.btn.cancel': 'Cancel',
    'new_ritual.btn.submit': 'Schedule Ritual',

    // --- APP TITLES ---
    'page.mission': 'Our Mission',
    'page.success': 'Success Stories',
    'page.pricing': 'Pricing',
    'page.accessibility': 'Accessibility Statement',
    'page.privacy': 'Privacy Policy',
    'page.cookies': 'Cookie Policy',
    'page.legal': 'Legal Notice',
    'page.mission.content': 'Empowering neurodiverse teams through clarity and empathy.',
    'page.success.content': 'Discover how leading companies are transforming their culture.',
    'page.pricing.content': 'Flexible plans for teams of all sizes.',
    'page.accessibility.content': 'Committed to WCAG 2.2 AAA.',
    'page.privacy.content': 'Your data is yours. Total transparency.',
    'page.cookies.content': 'Only the essentials to make the platform work.',
    'page.legal.content': 'Teamworkz legal information.',
  },
  'pt-br': {
    // --- SETTINGS (Existing) ---
    'settings.title': 'Configurações de Idioma e Região',
    'settings.desc': 'Personalize sua experiência no PACTO para se adequar à sua localização e preferências de trabalho.',
    'label.language': 'Idioma da plataforma',
    'label.region': 'País/Região',
    'label.timezone': 'Fuso Horário',
    'label.dateformat': 'Formato de Data/Hora',
    'settings.date_format.dmy_24': 'DD/MM/AAAA (24h)',
    'settings.date_format.dmy_12': 'DD/MM/AAAA (12h am/pm)',
    'settings.date_format.mdy_12': 'MM/DD/AAAA (12h am/pm)',
    'settings.date_format.ymd_24': 'AAAA-MM-DD (24h)',
    'tip.title': 'Por que isso é importante?',
    'tip.desc': 'Configurar seu fuso horário correto ajuda sua equipe a respeitar suas horas de "Deep Work" e sincronizar melhor as reuniões.',
    'btn.cancel': 'Cancelar',
    'btn.save': 'Salvar alterações',
    'btn.saving': 'Salvando...',
    'region.select': 'Selecione seu país',
    'timezone.select': 'Selecionar...',
    'back': 'Voltar',

    // --- NAVIGATION ---
    'nav.dashboard': 'Início',
    'nav.my_agreements': 'Meus Acordos',
    'nav.my_commitments': 'Meus Compromissos',
    'nav.team': 'Minha Equipe',
    'nav.rituals': 'Rituais',
    'nav.achievements': 'Conquistas',
    'nav.inbox': 'Caixa de Entrada',
    'nav.reports': 'Relatórios',
    'nav.clarity_kits': 'Kits de Clareza',
    'nav.profile': 'Meu Perfil',
    'nav.help': 'Ajuda',
    'nav.logout': 'Sair',

    // --- TIMEZONES ---
    'timezone.utc-12': 'Linha Internacional de Data Oeste',
    'timezone.utc-11': 'Ilha Midway, Samoa',
    'timezone.utc-10': 'Havaí',
    'timezone.utc-09': 'Alasca',
    'timezone.utc-08': 'Hora do Pacífico (EUA e Canadá)',
    'timezone.utc-07': 'Hora da Montanha (EUA e Canadá)',
    'timezone.utc-06': 'Hora Central (EUA e Canadá), Cidade do México',
    'timezone.utc-05': 'Hora do Leste (EUA e Canadá), Bogotá',
    'timezone.utc-04': 'Hora do Atlântico (Canadá), Santiago',
    'timezone.utc-03': 'Buenos Aires, Brasília',
    'timezone.utc-02': 'Atlântico Central',
    'timezone.utc-01': 'Açores, Cabo Verde',
    'timezone.utc+00': 'Londres, Dublin, Lisboa',
    'timezone.utc+01': 'Madri, Paris, Berlim, Roma',
    'timezone.utc+02': 'Atenas, Bucareste, Istambul',
    'timezone.utc+03': 'Moscou, São Petersburgo',
    'timezone.utc+04': 'Abu Dhabi, Mascate',
    'timezone.utc+05': 'Islamabad, Karachi',
    'timezone.utc+06': 'Almaty, Dhaka',
    'timezone.utc+07': 'Bangkok, Hanói, Jacarta',
    'timezone.utc+08': 'Pequim, Hong Kong, Cingapura',
    'timezone.utc+09': 'Tóquio, Seul',
    'timezone.utc+10': 'Sydney, Melbourne',
    'timezone.utc+11': 'Ilhas Salomão, Nova Caledônia',
    'timezone.utc+12': 'Fiji, Kamchatka',

    // --- LANDING PAGE ---
    'landing.nav.mission': 'Missão',
    'landing.nav.pillars': 'Pilares',
    'landing.nav.tools': 'Ferramentas',
    'landing.nav.start': 'Começar',
    'landing.hero.badge': 'Inovação Neurodiversa',
    'landing.hero.title': 'Da Intenção à Prática',
    'landing.hero.subtitle': 'Uma plataforma digital projetada para inclusão neurodiversa e acordos operacionais reais. Acessível, clara e construída para humanos.',
    'landing.hero.cta': 'Criar minha conta',
    'landing.pillars.title': 'Nossos Pilares',
    'landing.pillars.subtitle': 'PACTO reduz a carga cognitiva priorizando a estrutura visual e a segurança psicológica.',
    'landing.pillars.1.title': 'Segurança Psicológica',
    'landing.pillars.1.desc': 'Criamos ciclos de feedback seguros onde cada membro compartilha suas necessidades cognitivas.',
    'landing.pillars.2.title': 'Clareza Operacional',
    'landing.pillars.2.desc': 'Eliminamos a ambiguidade. Definimos expectativas claras e canais eficazes para todos.',
    'landing.pillars.3.title': 'Neuroinclusão',
    'landing.pillars.3.desc': 'Ferramentas criadas para acomodar TDAH, Autismo e diversos estilos de processamento.',
    'landing.tools.title': 'Ferramentas Visuais',
    'landing.tools.subtitle': 'Projetamos interfaces que reduzem o ruído e maximizam a clareza.',
    'landing.tools.1.title': 'Canvas de Acordos',
    'landing.tools.1.desc': 'Visualize todas as normas operacionais em um único lugar acessível.',
    'landing.tools.2.title': 'Kits de Clareza',
    'landing.tools.2.desc': 'Cartões pré-desenhados para resolver conflitos comuns de comunicação.',
    'landing.tools.3.title': 'Rituais de Replay',
    'landing.tools.3.desc': 'Estruturas para reuniões que garantem que todos estejam alinhados.',
    'landing.cta.title': 'Pronto para construir uma cultura verdadeiramente inclusiva?',
    'landing.cta.subtitle': 'Junte-se a empresas que já usam o PACTO para melhorar a clareza e a empatia operacional.',
    'landing.cta.btn': 'Começar grátis hoje',
    'landing.footer.desc': 'Plataforma de acordos vivos para inclusão laboral neurodiversa. Projetamos estruturas que permitem que cada mente trabalhe melhor.',

    // --- RITUALS ---
    'ritual.title': 'Rituais de Equipe',
    'ritual.desc': 'Gerencie sua energia cognitiva e colaborativa. Sem grades, apenas clareza.',
    'ritual.view.scheduled': 'Programados',
    'ritual.view.prep': 'A Preparar',
    'ritual.view.drafts': 'Rascunhos',
    'ritual.view.archived': 'Arquivados',
    'ritual.btn.schedule': 'Programar',
    'ritual.section.today': 'Hoje',
    'ritual.energy.load': 'Carga',
    'ritual.energy.level.high': 'Alta',
    'ritual.energy.level.medium': 'Média',
    'ritual.energy.level.optimal': 'Ótima',
    'ritual.energy.level.low': 'Baixa',
    'ritual.empty.title': 'Sua agenda de rituais está vazia',
    'ritual.empty.desc': 'Os rituais ajudam sua equipe a sincronizar sem esgotar sua energia. Crie o primeiro agora!',
    'ritual.btn.create_first': 'Criar meu primeiro ritual',

    // Ritual Types & Status
    'ritual.type.sync': 'Sincronização',
    'ritual.type.focus': 'Foco Profundo',
    'ritual.type.social': 'Social',
    'ritual.type.strategy': 'Estratégia',
    'ritual.status.completed': 'Concluído',
    'ritual.status.automatic': 'Automático',
    'ritual.status.no_notifications': 'Sem notificações',

    // Preparation View
    'ritual.prep.attention': 'Requer Atenção',
    'ritual.prep.desc': 'Você tem rituais futuros que ainda não têm agenda ou materiais preparados.',
    'ritual.prep.next': 'Próximo Ritual',
    'ritual.prep.btn': 'Preparar Agora',
    'ritual.prep.no_participants': 'Sem Agenda',
    'ritual.prep.participants': 'participantes',
    'ritual.prep.empty': 'Não há mais rituais pendentes de preparação.',

    // Drafts & Archived
    'ritual.drafts.empty.title': 'Sem rascunhos',
    'ritual.drafts.btn': 'Criar novo ritual',
    'ritual.archived.restore': 'Restaurar',
    'ritual.history.btn': 'Ver histórico completo',
    'ritual.history.link': 'Ver histórico de rituais passados',

    // Widgets (Right Sidebar)
    'ritual.widget.energy.title': 'Sugestões de Energia',
    'ritual.widget.analysis': 'Análise de hoje',
    'ritual.widget.level': 'Nível de Carga',
    'ritual.widget.msg.high': 'Detectamos {count} rituais. Sua carga cognitiva está acima da média recomendada.',
    'ritual.widget.msg.optimal': 'Sua carga de rituais está equilibrada. Bom momento para trabalho profundo.',
    'ritual.widget.suggestion': 'Sugestão: Bloqueie 15 min após o almoço para desconexão sensorial.',

    'ritual.widget.tools.title': 'Ferramentas Rápidas',
    'ritual.widget.pomodoro': 'Modo Pomodoro',
    'ritual.widget.pomodoro.desc': '25m foco / 5m pausa',
    'ritual.widget.mute': 'Silenciar Tudo',
    'ritual.widget.mute.desc': 'Até as 17:00',
    'ritual.widget.calendar.events': 'Eventos de Equipe',

    // --- ADMIN DASHBOARD ---
    'admin.badge': 'Visão de Administrador',
    'admin.title': 'Painel de Controle',
    'admin.subtitle': 'Gestão global de {name}.',
    'admin.btn.switch': 'Ir para Perfil Pessoal',
    'admin.metric.health': 'Saúde Organizacional',
    'admin.metric.health.desc': 'Baseado na adoção de acordos e feedback.',
    'admin.metric.members': 'Membros Ativos',
    'admin.metric.members.suffix': 'licenças',
    'admin.metric.agreements': 'Acordos Vigentes',
    'admin.metric.agreements.total': 'Total',
    'admin.btn.manage_team': 'Gerenciar Equipe',
    'admin.btn.templates': 'Ver Biblioteca de Modelos',
    'admin.actions.title': 'Ações Rápidas',
    'admin.action.invite': 'Convidar Usuários',
    'admin.action.teams': 'Gerenciar Equipes',
    'admin.action.reports': 'Ver Relatórios',
    'admin.action.accessibility': 'Configurar Acessibilidade',
    'admin.activity.title': 'Atividade da Organização',

    // --- DASHBOARD ---
    'dash.welcome': 'Olá, {name}',
    'dash.subtitle': 'Seu espaço pessoal de clareza e acordos.',
    'dash.btn.library': 'Explorar Biblioteca',
    'dash.btn.new': 'Novo Acordo',
    'dash.section.agreements': 'Meus Acordos Vivos',
    'dash.link.viewall': 'Ver todos',
    'dash.empty.title': 'Ainda não tem acordos',
    'dash.empty.desc': 'Crie um novo para melhorar a clareza com sua equipe.',
    'dash.empty.btn': 'Criar meu primeiro acordo',
    'dash.widget.wellbeing': 'Meu Bem-estar',
    'dash.widget.clarity': 'Clareza',
    'dash.widget.tostart': 'A iniciar',
    'dash.widget.ready': 'Tudo pronto! Você está alinhado e pronto para colaborar.',
    'dash.widget.nodata': 'Sem dados ainda. Crie seu primeiro Acordo Vivo.',
    'dash.tools.title': 'Ferramentas Pessoais',
    'dash.tools.focus.active': 'Foco Ativo',
    'dash.tools.focus.start': 'Iniciar Modo Foco',
    'dash.tools.focus.muting': 'Silenciando notificações',
    'dash.tools.focus.desc': 'Silenciar notificações por 1h',
    'dash.tools.clarity.title': 'Ver Clarity Cards',
    'dash.tools.clarity.desc': 'Guias visuais de comunicação',
    'dash.tip.title': 'Dica do Dia',
    'dash.tip.btn.idle': 'Enviar Dica para Equipe',
    'dash.tip.btn.sending': 'Enviando...',
    'dash.tip.btn.success': 'Enviado!',

    // --- GLOBAL ---
    'global.menu': 'Menu',
    'global.back_home': 'Voltar ao Início',
    'global.notifications': 'Notificações',
    'global.brand_suffix': 'by Teamworkz',
    'global.copyright': 'Todos os direitos reservados.',
    'global.rights': 'Compatível com WCAG 2.2 Nível AAA',
    'global.btn.close': 'Fechar',

    // --- LAYOUT ---
    'layout.mobile.menu': 'Menu',
    'layout.mobile.back': 'Voltar ao Início',

    // --- LANDING FOOTER ---
    'landing.footer.platform': 'Plataforma',
    'landing.footer.legal': 'Legal',
    'landing.footer.mission': 'Nossa Missão',
    'landing.footer.success': 'Casos de Sucesso',
    'landing.footer.pricing': 'Preços',
    'landing.footer.contact': 'Formulário de Contato',
    'landing.footer.accessibility': 'Declaração de Acessibilidade',
    'landing.footer.privacy': 'Política de Privacidade',
    'landing.footer.cookies': 'Política de Cookies',
    'landing.footer.legal_notice': 'Aviso Legal',

    // --- DASHBOARD ---
    'dash.view.personal': 'Visão Pessoal',
    'dash.view.admin': 'Visão de Admin',
    'dash.return_admin': 'Voltar ao Painel Admin',
    'dash.tag.inclusion': 'Inclusão',
    'dash.tag.wellbeing': 'Bem-estar',

    // --- RITUALS ---
    'ritual.view.label': 'Vistas',
    'ritual.card.prepare.title': 'Replay Semanal',
    'ritual.card.prepare.desc': 'Sincronização de equipe. Revise acordos anteriores e defina o tom da sessão.',

    // --- NEW RITUAL ---
    'new_ritual.title': 'Novo Ritual de Replay',
    'new_ritual.subtitle': 'Defina os detalhes para sua próxima sessão de alinhamento.',
    'new_ritual.btn.close': 'Fechar',
    'new_ritual.accessibility.title': 'Dica de Acessibilidade',
    'new_ritual.accessibility.desc': 'Enviar a agenda com 24 horas de antecedência ajuda todos os participantes a se prepararem melhor e reduz a ansiedade.',
    'new_ritual.accessibility.link': 'Ver mais dicas',
    'new_ritual.label.title': 'Título do Ritual',
    'new_ritual.placeholder.title': 'Ex. Sincronização Semanal de Design',
    'new_ritual.label.date': 'Data',
    'new_ritual.label.time': 'Hora',
    'new_ritual.label.participants': 'Participantes',
    'new_ritual.placeholder.participants': 'Adicionar + Enter...',
    'new_ritual.label.objective': 'Objetivo da Sessão',
    'new_ritual.placeholder.objective': 'Descreva brevemente o que se espera alcançar nesta sessão...',
    'new_ritual.section.agreements': 'Vincular Acordos Ativos',
    'new_ritual.section.agreements.desc': 'Selecione um acordo para adicioná-lo automaticamente à agenda de revisão.',
    'new_ritual.section.agenda': 'Agenda do Ritual',
    'new_ritual.btn.add_agreement': 'Adicionar outro acordo',
    'new_ritual.btn.cancel': 'Cancelar',
    'new_ritual.btn.submit': 'Programar Ritual',

    // --- APP TITLES ---
    'page.mission': 'Nossa Missão',
    'page.success': 'Casos de Sucesso',
    'page.pricing': 'Preços',
    'page.accessibility': 'Declaração de Acessibilidade',
    'page.privacy': 'Política de Privacidade',
    'page.cookies': 'Política de Cookies',
    'page.legal': 'Aviso Legal',
    'page.mission.content': 'Empoderando equipes neurodiversas através da clareza e empatia.',
    'page.success.content': 'Descubra como empresas líderes estão transformando sua cultura.',
    'page.pricing.content': 'Planos flexíveis para equipes de todos os tamanhos.',
    'page.accessibility.content': 'Comprometidos com WCAG 2.2 AAA.',
    'page.privacy.content': 'Seus dados são seus. Transparência total.',
    'page.cookies.content': 'Apenas o essencial para que a plataforma funcione.',
    'page.legal.content': 'Informações legais da Teamworkz.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es-la');


  // Helper helper to map display names to internal keys
  const getLanguageCode = (displayName: string): string => {
    const lower = displayName.toLowerCase();
    if (lower.includes('español')) return 'es-la'; // Map all Spanish to es-la for now
    if (lower.includes('english')) return 'en-us'; // Map all English to en-us
    if (lower.includes('português')) return 'pt-br'; // Map all Portuguese to pt-br
    return 'es-la'; // Default fallback
  };

  const t = (key: string): string => {
    const code = getLanguageCode(language);
    const langDict = translations[code] || translations['es-la'] || {};
    return langDict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
